### ISSUE TITLE
Not working when opening a file

### ISSUE THREAD

**Issue by somepaulo** [coderstephen/atom-gtk-dark-theme#5]
When Atom isn't running and I open a file from the system or tmp, Atom loads with the light bar.
When I first open Atom, and then open a file either by double clicking in the file manager or through the Atom menus, the bar is rendered dark a second after loading the light one.
Using Gnome 3.24 on Arch with Wayland.

**Comment by potocpav** [comment]
This seems to be already resolved in master. The Atom package is just outdated.

**Comment by somepaulo** [comment]
Thanks for the tip @potocpav 
Seems like it's fixed indeed. I replaced the code in my .atom/packages folder with the one form master and the dark bar works alright since then.
